/* Generated by MyraPad at 16.08.2022 15:26:35 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using Myra.Graphics2D.UI.Styles;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace Scorpia.Game.Menu
{
	partial class MainMenu: Panel
	{
		private void BuildUI()
		{
			Id = "MainMenu";

			Background = Stylesheet.Current.Atlas.Regions["menu_background"];
			
			var label1 = new Label();
			label1.Text = "Hallo there";
			label1.Font = Stylesheet.Current.Fonts["menu"];

			var button = new ImageTextButton();
			button.Text = "Hello";
			button.Font = Stylesheet.Current.Fonts["menu"];
			
			// Widgets.Add(label1);
			Widgets.Add(button);
		}
	}
}
